version: '3.8'

services:
  postgreSQL:
    image: postgres:16.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    networks:
      - grafana_dashboard
networks:
  grafana_dashboard:
    external: true
  
