drop table if exists sensor cascade;
drop table if exists fire cascade;
drop table if exists sensor_event cascade;
drop table if exists team cascade;
drop table if exists fire_station cascade;
drop table if exists fire_truck cascade cascade;
drop table if exists fire_truck_type cascade;
create table sensor(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  longitude decimal(9, 6) not null,
  latitude decimal(9, 6) not null
);
create table fire (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  started_at timestamp not null,
  ended_at timestamp
);
create table sensor_event(
  sensor_id bigint references sensor(id),
  fire_id bigint references fire(id),
  update_at timestamp,
  level integer not null,
  constraint sensor_event_pkey primary key(sensor_id, fire_id, update_at)
);
create table fire_station(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  longitude decimal(9, 6) not null,
  latitude decimal(9, 6) not null
);
create table team(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  name varchar(50) not null
);
create table fire_truck_type(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  label varchar(50) not null,
  speed integer not null,
  -- Vitesse du véhicule
  power_factor integer not null --Puissance du véhicule
);
create table fire_truck(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  fire_station_id bigint references fire_station(id) not null,
  fire_truck_type_id bigint references fire_truck_type(id) not null,
  longitude decimal(3, 20),
  latitude decimal(3, 20)
);
create table intervention(
  team_id bigint references team(id) not null,
  fire_truck_id bigint references fire_truck(id) not null,
  fire_id bigint references fire(id) not null,
  path path,
  constraint intervention_pkey primary key(team_id, fire_truck_id, fire_id)
);
create table fire_fighter(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
  firstname varchar(50) not null,
  surname varchar(50) not null,
  energy integer default 10,
  fire_station_id bigint references fire_station(id) not null,
  team_id bigint references team(id)
);